### PR TITLE
Fixed 'regeneratorRuntime not defined' error

### PR DESCRIPTION
**Pull request by fredrik955**
Missed Babel transform runtime polyfill

### CODE REVIEW

**Comment by swagatha-christie** [comment]
By analyzing the blame information on this pull request, we identified @oliverwoodings to be a potential reviewer

**Comment by oliverwoodings** [comment]
Thanks for the PR! I'm a bit confused why this is needed - do the tests not run without it or something?

**Comment by jakeorr** [comment]
@oliverwoodings: I start up my babelled app, it imports `import Upload from 'gcs-browser-upload';` and immediately crashes with 
```
Upload.js:12 Uncaught ReferenceError: regeneratorRuntime is not defined
    at Upload.js:12
```

**Comment by oliverwoodings** [comment]
@jakeorr this library requires `regeneratorRuntime` to be available globally - it is written in ES7 and makes use of `async/await`, which gets downcompiled into generators. You can find out about `regenerator-runtime` [here](https://www.npmjs.com/package/regenerator-runtime) - it is the generator runtime used by babel/facebook.

**Comment by jakeorr** [comment]
Got it! Thanks.

**Comment by jjPlusPlus** [comment]
@oliverwoodings might be good to add that to the README

**Pull request closed without merging**
